### ISSUE TITLE
Getting Error while deploying MyNFT.cdc

### ISSUE THREAD

**Issue by ashlinSajan** [jacob-tucker/nftdapp-tutorial#1]
![MyNFT_errors](https://user-images.githubusercontent.com/34328137/201875660-83f235bf-72ca-4e3c-a694-e2d5a95185a6.JPG)
Hi @jacob-tucker getting the following issue while trying MyNFT.cdc in the NFTMarketplace demo video you showed.
Please help with this

**Comment by jacob-tucker** [comment]
Hey there! To fix, change that line to:

`return &self.ownedNFTs[id] as &NonFungibleToken.NFT?`

There was an update to Cadence that effected this :)

For more help, come join Emerald Academy!: https://discord.gg/qzemWSxm2u

**Comment by ashlinSajan** [comment]
> Hey there! To fix, change that line to:
> 
> `return &self.ownedNFTs[id] as &NonFungibleToken.NFT?`
> 
> There was an update to Cadence that effected this :)
> 
> For more help, come join Emerald Academy!: https://discord.gg/qzemWSxm2u

Thanks for the reply @jacob-tucker still getting issues after editing the line
![cadence_error](https://user-images.githubusercontent.com/34328137/202103002-1e353d74-968d-43ea-abf1-4c628ade9c06.JPG)

**Comment by jacob-tucker** [comment]
Ah, you’ll actually need to change it to:

`return (&self.ownedNFTs[id] as &NonFungibleToken.NFT?)!`

If you have further questions, please join the Emerald Academy discord linked above :)
